use code_reload::hotreload;

struct Model {
    value: i32,
}

impl Model {
    // TODO - need to add usages for types used in macro target
    // right now needs fully-qualified path because compiler
    // can not understand what `Pin` is in autogenerated code
    #[hotreload(runtime)]
    pub fn r#static(kavo: Box<Self>, chevo: Pin<Self>) {
        let _nothing = ();
    }
}
